[build]
builder = "NIXPACKS"

[deploy]
startCommand = "gunicorn wsgi:app --bind 0.0.0.0:$PORT --workers 4 --timeout 120"
healthcheckPath = "/health"
healthcheckTimeout = 100
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3

[[services]]
name = "web"